### ISSUE TITLE
discountAllAbove - nu calculeaza corect totalul

### ISSUE THREAD

**Issue by stardand** [OblioSoftware/OblioApi#2]
Cand se trimite discount procentual pentru toate produsele, valoarea procentuala se adauga corect in factura, dar totalul de plata este incorect.

{
    "name": "Discount 10% Test",
    "discount": 10,
    "discountType": "procentual",
    "discountAllAbove": 1
}

1 serv1 400.00
2 serv2 6.00
3 Discount 10% -40.60
Total plata 405.40 RON

![image](https://github.com/user-attachments/assets/3818c581-e720-4d86-a297-4b1009c7de9c)

**Comment by MihaiCraciun88** [comment]
Multumim, s-a rezolvat
