### ISSUE TITLE
storage/access_token

### ISSUE THREAD

**Issue by stardand** [OblioSoftware/OblioApi#3]
Salut, incerc sa inteleg daca pot sa folosesc api-ul pentru un soft de gestiune laboratoare (Miiosmile) si am cateva intrebari.. 

API-ul Oblio poate fi folosit pentru un CRM (in care se logheaza utilizatori care au cont si in aplicatia Oblio)? 

Daca un utilizator cu "client_id" si "client_secret" unic, primeste un token (valabil o ora) care se va salva in fisierul storage/access_token.php, atunci, un alt utilizator (cu alt "client_id" si "client_secret") poate folosi acelasi token salvat in acest fisier? ... sau va genera alt token si va suprascrie fisierul??

Multumesc.

**Comment by MihaiCraciun88** [comment]
Salut, 

Scriptul care stocheaza token-ul intr-un fisier este un exemplu de implementare, nu recomand sa se salveze asa, ci in baza de date.
Alte exemple ar fi:
 - Woocommerce: https://github.com/OblioSoftware/oblio-woocommerce/blob/main/src/Api/AccessTokenHandler.php
 - Prestashop: https://github.com/OblioSoftware/oblio-prestashop/blob/main/classes/OblioApiPrestashopAccessTokenHandler.php

Acestea ar trebui sa implementeze interfata AccessTokenHandlerInterface.

Daca aplicatia in care se face implementarea suporta mai multi utilizatori ar trebui separate datele pe utilizator.

Multumesc
